mqtt:
  enabled: False

# Standard CPU Detector compatible with Intel Haswell i5-4308U
detectors:
  cpu:
    type: cpu

# High-speed WebRTC / MSE Live Viewing engine
go2rtc:
  streams:
    cam1_macro:
      - rtsp://192.168.0.245:8554/cam1
    cam2_macro:
      - rtsp://192.168.0.245:8554/cam2
    cam3_yi_storage:
      - rtsp://192.168.0.245:8554/cam3
    cam4_yi_camara2:
      - rtsp://192.168.0.245:8554/cam4

cameras:
  cam1_macro:
    ffmpeg:
      inputs:
        - path: rtsp://192.168.0.245:8554/cam1
          input_args: preset-rtsp-generic
          roles:
            - detect
            - record
    detect:
      width: 640
      height: 480
      fps: 5
    onvif:
      host: 192.168.0.238
      port: 8899

  cam2_macro:
    ffmpeg:
      inputs:
        - path: rtsp://192.168.0.245:8554/cam2
          input_args: preset-rtsp-generic
          roles:
            - detect
            - record
    detect:
      width: 1280
      height: 720
      fps: 5
    onvif:
      host: 192.168.0.11
      port: 8899

  cam3_yi_storage:
    ffmpeg:
      inputs:
        - path: rtsp://192.168.0.245:8554/cam3
          input_args: preset-rtsp-generic
          roles:
            - detect
            - record
    detect:
      width: 1280
      height: 720
      fps: 5
    onvif:
      host: 192.168.0.245
      port: 8898

  cam4_yi_camara2:
    ffmpeg:
      inputs:
        - path: rtsp://192.168.0.245:8554/cam4
          input_args: preset-rtsp-generic
          roles:
            - detect
            - record
    detect:
      width: 1280
      height: 720
      fps: 5
    onvif:
      host: 192.168.0.245
      port: 8897

record:
  enabled: True
  retain:
    days: 3
    mode: all
  alerts:
    retain:
      days: 14

snapshots:
  enabled: True
  retain:
    default: 14
