version: "3.9"

services:
  frigate:
    container_name: frigate
    privileged: true
    restart: unless-stopped
    image: ghcr.io/blakeblackshear/frigate:stable
    shm_size: "256mb"
    volumes:
      - ./config.yml:/config/config.yml
      - ./storage:/media/frigate
      - type: tmpfs
        target: /tmp/cache
        tmpfs:
          size: 1000000000
    ports:
      - "0.0.0.0:8971:8971"       # Frigate Web UI (Auth / HTTPS) - LAN: http://192.168.0.46:8971
      - "0.0.0.0:5001:5000"       # Frigate Web UI / API (Unauth) - LAN: http://192.168.0.46:5001
      - "0.0.0.0:8555:8554"       # RTSP restream from go2rtc - LAN: rtsp://192.168.0.46:8555
      - "0.0.0.0:8556:8555/tcp"   # WebRTC over TCP
      - "0.0.0.0:8556:8555/udp"   # WebRTC over UDP
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      - FRIGATE_RTSP_PASSWORD=password

